version: '3.8'

services:
  db:
    container_name: ticket4u_db
    image: postgres:14.1-alpine
    restart: no
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

