"""initial migrate

Revision ID: 44fcf034a3d4
Revises: 
Create Date: 2024-09-30 09:04:14.995301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fcf034a3d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cinemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Cinemas_id'), 'Cinemas', ['id'], unique=False)
    op.create_table('Discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('amountx100', sa.Integer(), nullable=True),
    sa.Column('percentx100', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Discounts_id'), 'Discounts', ['id'], unique=False)
    op.create_table('Movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('last_showing_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Movies_id'), 'Movies', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_registration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_table('Halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['Cinemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Halls_id'), 'Halls', ['id'], unique=False)
    op.create_table('Payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Payments_id'), 'Payments', ['id'], unique=False)
    op.create_table('Refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refund_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Refunds_id'), 'Refunds', ['id'], unique=False)
    op.create_table('Seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=True),
    sa.Column('row', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['Halls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Seats_id'), 'Seats', ['id'], unique=False)
    op.create_table('Showings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['Halls.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Showings_id'), 'Showings', ['id'], unique=False)
    op.create_table('Tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showing_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('purchase_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pricex100', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discount_id'], ['Discounts.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['Seats.id'], ),
    sa.ForeignKeyConstraint(['showing_id'], ['Showings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tickets_id'), 'Tickets', ['id'], unique=False)
    op.create_table('Ticket_Payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amountx100', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['Payments.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['Tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ticket_Payments_id'), 'Ticket_Payments', ['id'], unique=False)
    op.create_table('Ticket_Payment_Refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_payment_id', sa.Integer(), nullable=True),
    sa.Column('amountx100', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('refund_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['refund_id'], ['Refunds.id'], ),
    sa.ForeignKeyConstraint(['ticket_payment_id'], ['Ticket_Payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Ticket_Payment_Refunds_id'), 'Ticket_Payment_Refunds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Ticket_Payment_Refunds_id'), table_name='Ticket_Payment_Refunds')
    op.drop_table('Ticket_Payment_Refunds')
    op.drop_index(op.f('ix_Ticket_Payments_id'), table_name='Ticket_Payments')
    op.drop_table('Ticket_Payments')
    op.drop_index(op.f('ix_Tickets_id'), table_name='Tickets')
    op.drop_table('Tickets')
    op.drop_index(op.f('ix_Showings_id'), table_name='Showings')
    op.drop_table('Showings')
    op.drop_index(op.f('ix_Seats_id'), table_name='Seats')
    op.drop_table('Seats')
    op.drop_index(op.f('ix_Refunds_id'), table_name='Refunds')
    op.drop_table('Refunds')
    op.drop_index(op.f('ix_Payments_id'), table_name='Payments')
    op.drop_table('Payments')
    op.drop_index(op.f('ix_Halls_id'), table_name='Halls')
    op.drop_table('Halls')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Movies_id'), table_name='Movies')
    op.drop_table('Movies')
    op.drop_index(op.f('ix_Discounts_id'), table_name='Discounts')
    op.drop_table('Discounts')
    op.drop_index(op.f('ix_Cinemas_id'), table_name='Cinemas')
    op.drop_table('Cinemas')
    # ### end Alembic commands ###
